name: Deploy Serverless Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (prod)
      - dev    # Trigger on pushes to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stage: [dev, prod]  # Define the stages for the deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Deploy to Serverless
        run:  ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: npx serverless deploy --stage ${{ matrix.stage }}  # Deploy to the corresponding stage
        if: github.ref == 'refs/heads/${{ matrix.stage }}'  # Only run when pushing to the corresponding branch
